### ISSUE TITLE
Share discriminator checkpoint file？

### ISSUE THREAD

**Issue by DinnerWhen** [zjbthomas/TMO-GAN#1]
Hello, thanks for your work. I would like to do some additional work based on your network, so could you please share the weights of the Discriminator?

**Comment by zjbthomas** [comment]
Thanks for your interest in our work. The weights of the discriminator can be found [here](https://github.com/zjbthomas/TMO-GAN/blob/main/pretrained/discriminator.pth).

**Comment by DinnerWhen** [comment]
Thank you very much for your prompt reply.
